# Notebook 01

In [1]:
import tensorflow as tf
tf.random.set_seed(42)
print(tf.__version__)

2.8.0


In [3]:
tf.config.experimental.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [6]:
x = tf.constant(7)
x

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [7]:
x.ndim

0

In [8]:
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [9]:
matrix.ndim

2

In [10]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [11]:
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [12]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [13]:
unchangeable_tensor[0].assign(7)
unchangleable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [14]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_1 = random_1.normal(shape=(3, 2)) # create tensor from a normal distribution 
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [15]:
tf.ones(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [16]:
tf.zeros(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [21]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
A = tf.constant(numpy_A,  
                shape=[2, 4, 3]) # note: the shape total (2*4*3) has to match the number of elements in the array
print(numpy_A,A)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]], shape=(2, 4, 3), dtype=int32)


In [23]:
tensor = tf.constant([[10, 7], [3, 4]])
print(tensor + 10)

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)


In [24]:
print(tf.multiply(tensor, 10))

tf.Tensor(
[[100  70]
 [ 30  40]], shape=(2, 2), dtype=int32)


In [25]:
print(tf.matmul(tensor, tensor))

tf.Tensor(
[[121  98]
 [ 42  37]], shape=(2, 2), dtype=int32)


In [27]:
# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
print(X, Y)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32) tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)


In [28]:
# Try to matrix multiply them (will error)
X @ Y

InvalidArgumentError: Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

In [30]:
# Try matrix multiplication with reshaped Y
print(X @ tf.reshape(Y, shape=(2, 3)))

tf.Tensor(
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]], shape=(3, 3), dtype=int32)


In [32]:
# Example of transpose (3, 2) -> (2, 3)
print(tf.transpose(X))

tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)


In [33]:
# Perform the dot product on X and Y (requires X to be transposed)
print(tf.tensordot(tf.transpose(X), Y, axes=1))

tf.Tensor(
[[ 89  98]
 [116 128]], shape=(2, 2), dtype=int32)


In [34]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])

# Create a new tensor with default datatype (int32)
C = tf.constant([1, 7])
print(B, C)

tf.Tensor([1.7 7.4], shape=(2,), dtype=float32) tf.Tensor([1 7], shape=(2,), dtype=int32)


In [35]:
# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
print(B)

tf.Tensor([1.7 7.4], shape=(2,), dtype=float16)


In [36]:
# Create a tensor with 50 random values between 0 and 100
E = tf.constant(np.random.randint(low=0, high=100, size=50))
print(E)

tf.Tensor(
[46 49 64  3 58 42 86 85 25 34 70 11 95 76 64 37 64 19 70 54 61 38 35 54
 97 64 11 52 34 90 27 27 95 40 34 67 63 94 30 72 97 48 89 11 81 64 37 20
  0 53], shape=(50,), dtype=int32)


In [37]:
# Find the mean
print(tf.reduce_mean(E))

tf.Tensor(52, shape=(), dtype=int32)


In [38]:
# Find the maximum element position of F
print(tf.argmax(E).numpy())

24


In [40]:
# Create a rank 5 (5 dimensions) tensor of 50 numbers between 0 and 100
G = tf.constant(np.random.randint(0, 100, 224*224*3), shape=(1, 224,224,3))
# G.shape, G.ndim
print(G)

tf.Tensor(
[[[[91  0 78]
   [76 78 85]
   [51 23 26]
   ...
   [31 65 98]
   [94 39 65]
   [33 77 26]]

  [[42 76 99]
   [76 73 78]
   [ 6 25  9]
   ...
   [62 81 24]
   [88 91 72]
   [69 66 96]]

  [[48 62 76]
   [19  7 32]
   [43 63 97]
   ...
   [23 35 81]
   [43 35 29]
   [41  4 73]]

  ...

  [[64 49 99]
   [79 24 11]
   [40 76 13]
   ...
   [18 34 62]
   [ 8 64 85]
   [ 0 85 69]]

  [[46 94 16]
   [ 9 87  4]
   [44 24 88]
   ...
   [96 87 76]
   [78  1 83]
   [85 70 70]]

  [[77 89 45]
   [75 22 91]
   [33 61 36]
   ...
   [18 21 52]
   [91 63 14]
   [22 27 96]]]], shape=(1, 224, 224, 3), dtype=int32)


In [41]:
print(tf.squeeze(G))

tf.Tensor(
[[[91  0 78]
  [76 78 85]
  [51 23 26]
  ...
  [31 65 98]
  [94 39 65]
  [33 77 26]]

 [[42 76 99]
  [76 73 78]
  [ 6 25  9]
  ...
  [62 81 24]
  [88 91 72]
  [69 66 96]]

 [[48 62 76]
  [19  7 32]
  [43 63 97]
  ...
  [23 35 81]
  [43 35 29]
  [41  4 73]]

 ...

 [[64 49 99]
  [79 24 11]
  [40 76 13]
  ...
  [18 34 62]
  [ 8 64 85]
  [ 0 85 69]]

 [[46 94 16]
  [ 9 87  4]
  [44 24 88]
  ...
  [96 87 76]
  [78  1 83]
  [85 70 70]]

 [[77 89 45]
  [75 22 91]
  [33 61 36]
  ...
  [18 21 52]
  [91 63 14]
  [22 27 96]]], shape=(224, 224, 3), dtype=int32)


In [42]:
print(tf.squeeze(E))

tf.Tensor(
[46 49 64  3 58 42 86 85 25 34 70 11 95 76 64 37 64 19 70 54 61 38 35 54
 97 64 11 52 34 90 27 27 95 40 34 67 63 94 30 72 97 48 89 11 81 64 37 20
  0 53], shape=(50,), dtype=int32)


In [43]:
# Create a tensor from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
print(J)

tf.Tensor([ 3.  7. 10.], shape=(3,), dtype=float64)
