In [1]:
import torch

In [5]:
x = torch.tensor([1, 2, 3])
y = torch.zeros(2, 3)
z = torch.rand(3, 2)

x, y, z

(tensor([1, 2, 3]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[0.0615, 0.3939],
         [0.2952, 0.5358],
         [0.3174, 0.1157]]))

In [6]:
x+y

tensor([[1., 2., 3.],
        [1., 2., 3.]])

In [8]:
x*4

tensor([ 4,  8, 12])

In [13]:
torch.matmul(x.to(torch.float), z)

tensor([1.6040, 1.8125])

In [14]:
x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(3.0, requires_grad=True)

# Perform a computation
z = x**2 + y**3
print("Output tensor z:", z)

# Compute gradients
z.backward()
print("Gradient of x:", x.grad)
print("Gradient of y:", y.grad)

Output tensor z: tensor(31., grad_fn=<AddBackward0>)
Gradient of x: tensor(4.)
Gradient of y: tensor(27.)
